name: Build Image

on:
  push:
    branches: [ master ]

env:
  REGISTRY_IMAGE: indexyz/chuangmi-plug-exporter

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: Install dependencies
      run: yarn install

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.REGISTRY_IMAGE }}
        docker push ${{ env.REGISTRY_IMAGE }}
